AWSTemplateFormatVersion: "2010-09-09"
Description: "Master Template: Calls Networking, Security, and Compute Modules"

Parameters:
  KeyName:
    Description: KeyPair Name
    Type: AWS::EC2::KeyPair::KeyName
  MyPublicIP:
    Description: Your IP Address
    Type: String
    Default: 0.0.0.0/0
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id"
    Description: "Auto-resolve latest Ubuntu 22.04 LTS AMI ID in current Region"

Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./networking.yaml

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security.yaml
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VpcId
        MyPublicIP: !Ref MyPublicIP

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./compute.yaml
      Parameters:
        KeyName: !Ref KeyName
        LatestAmiId: !Ref LatestAmiId
        PublicSubnetId: !GetAtt NetworkingStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt NetworkingStack.Outputs.PrivateSubnetId
        PublicSecurityGroupId: !GetAtt SecurityStack.Outputs.PublicSecurityGroupId
        PrivateSecurityGroupId: !GetAtt SecurityStack.Outputs.PrivateSecurityGroupId

Outputs:
  SSHPublicCommand:
    Value: !Sub "ssh -i ${KeyName}.pem ubuntu@${ComputeStack.Outputs.PublicIP}"
  PrivateInstanceIP:
    Value: !GetAtt ComputeStack.Outputs.PrivateIP
